# Generated by Django 3.1.5 on 2021-01-15 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('address', models.CharField(db_index=True, max_length=50, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('category', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Категория')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('city', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Цена')),
                ('quantity', models.IntegerField(default=1, null=True, verbose_name='На складе')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('payment', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Платежная система')),
            ],
            options={
                'verbose_name': 'Платежная система',
                'verbose_name_plural': 'Платежные системы',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('chat_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='ID Пользователя')),
                ('username', models.CharField(max_length=50, verbose_name='Username')),
                ('referral', models.BigIntegerField(blank=True, null=True, verbose_name='Реферер')),
                ('ordered', models.BooleanField(default=False, verbose_name='Делал покупки')),
                ('successful_purchases', models.IntegerField(default=0, verbose_name='Кол-во успешных покупок')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='SuccessfulPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersmanage.user', verbose_name='ID Пользователя')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersmanage.goods', verbose_name='Товара')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersmanage.payment', verbose_name='Способ оплаты')),
            ],
            options={
                'verbose_name': 'Успешная покупка',
                'verbose_name_plural': 'Успешные покупки',
            },
        ),
        migrations.CreateModel(
            name='GoodsAndAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersmanage.address')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersmanage.goods')),
            ],
            options={
                'verbose_name': 'Товары-адрес',
                'verbose_name_plural': 'Товары-адреса',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='address',
            field=models.ManyToManyField(db_index=True, through='usersmanage.GoodsAndAddress', to='usersmanage.Address'),
        ),
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersmanage.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='goods',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersmanage.city', verbose_name='Город'),
        ),
        migrations.CreateModel(
            name='FailedPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersmanage.user', verbose_name='ID Пользователя')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersmanage.goods', verbose_name='Товара')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersmanage.payment', verbose_name='Способ оплаты')),
            ],
            options={
                'verbose_name': 'Неудачная покупка',
                'verbose_name_plural': 'Неудачные покупки',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersmanage.city', verbose_name='Город'),
        ),
    ]
