# Generated by Django 3.1.5 on 2021-01-18 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='city',
        ),
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='goodsandaddress',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersmanage.address', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='goodsandaddress',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersmanage.goods', verbose_name='Название товара'),
        ),
    ]
