# Generated by Django 3.1.5 on 2021-01-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0002_auto_20210118_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='photo_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
